### ISSUE TITLE
[BUG] Doesn't produce taxonomy - missing both a library and panda 3.0 issue

### ISSUE THREAD

**Issue by raw937** [amillard/tax_myPHAGE#15]
**Describe the bug**
Appears to be both a pandas 3.0 issue and a missing library. It doesn't produce a taxonomy either way. 

**To Reproduce**
```
taxmyphage -i UP30.fsa -o UP30_out -p UP30 -t 8
```
```
taxmyphage -i query.fasta -o out -p test -t 8
```

**Expected behavior**

**Screenshots**

=========================
TAXMYPHAGE version 0.3.1
=========================

--------------------------
Looking for database files
--------------------------

Found /home/docwhite/miniconda3/envs/taxmyphage/lib/python3.12/site-packages/taxmyphage/database/VMR.xlsx as expected
/home/docwhite/miniconda3/envs/taxmyphage/lib/python3.12/site-packages/taxmyphage/handle_files.py:114: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

  taxa_df["Genbank"].fillna("", inplace=True)
Found /home/docwhite/miniconda3/envs/taxmyphage/lib/python3.12/site-packages/taxmyphage/database/ICTV_2023.msh as expected
Found /home/docwhite/miniconda3/envs/taxmyphage/lib/python3.12/site-packages/taxmyphage/database/Bacteriophage_genomes.fasta.nhr as expected

------------------------------
Starting tax_my_phage analysis
------------------------------

Classifying:   0%|                                                                                                                                                                           | 0/1 [00:00<?, ?it/s]

Classifying UP30 in result folder UP30_out/Results_per_genome/UP30

-------------
MASH analysis
-------------

Number of phage genomes detected with mash distance of < 0.2 is:1

The mash distances obtained for this query phage:

+-----++-----+
| Minimum || Maximum |
+-----++-----+
| nan || nan |
+-----++-----+

Found 0 genera associated with this query genome

Classifying:   0%|                                                                                                                                                                           | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/docwhite/miniconda3/envs/taxmyphage/bin/taxmyphage", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/docwhite/miniconda3/envs/taxmyphage/lib/python3.12/site-packages/taxmyphage/__main__.py", line 124, in main
    all_classification(
  File "/home/docwhite/miniconda3/envs/taxmyphage/lib/python3.12/site-packages/taxmyphage/actions.py", line 140, in all_classification
    mash_df, accession_genus_dict = classification_mash(
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/docwhite/miniconda3/envs/taxmyphage/lib/python3.12/site-packages/taxmyphage/classify.py", line 187, in classification_mash
    keys = [k for k, v in accession_genus_dict.items() if v == unique_genera[0]]
                                                               ~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Please complete the following information:**

***OS:*** 

 - [X ] Linux
 - [ ] Windows
 - [ ] Mac

***taxmyPHAGE Version:***

   TAXMYPHAGE version 0.3.1

**Additional context**
From outfile
Reference,Query,distance,p-value,shared-hashes,ANI
mash: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory,,,,,

>query_UP30
ATGAGCAATACCAATCAGGAATTAAAAATCACCGATATGATTCGCCTAACCTGCGATGCA
ATGTACCGCGACAAAGGCATGAAAGAGTTCTCTTTCGTGGCTGATGATATGGCGAGAGAG
GCGGTAAAATTTTACTTCCGAGATCAGGATATTTCAGATGATGAGGTGGAGCGCGGAGCT
ACCGGGTGGGTGAACCAGAACCAGGGCGAGGTGGAGAAGCGATTCAAGTCGGCTTTCATC
ACCCCGATCATTACCCGACACTTCTGCAAGTATGGCAAGGTGGCAAAGGTTAAGGTAGGC
AGGAATGACGCAGCAATCACTATGATAACCGTTACCGTTACCGACGAAGAGGCTCCGGTG

query.fasta is from your website.

**Comment by tsp-kucbd** [comment]
It looks like you have a problem with the GNU Scientific Library (GSL) shared library, so your mash command does not work, and therefore you don't get any hits.

If you try
`ldd $(which mash)`

It should tell you that it is missing `libgsl.so.25`
If you installed mash via Conda, it should installed the correct version of libgsl too ...
Maybe reinstall mash?

**Comment by raw937** [comment]
I installed based on this command
```mamba create -n taxmyphage -c conda-forge -c bioconda taxmyphage
mamba activate taxmyphage

# If databases not installed, install them
taxmyphage install```

Which version of mash should be included? 
The pandas message isn't an issue?

Many thanks,
Rick

**Comment by amillard** [comment]
It is version mash 2.3 
The pandas warnings shouldnt stop it working 

Andy

**Comment by raw937** [comment]
installed mash. this library is missing -> libgsl.so.25 => not found

I tried sudo apt-get install libgsl-dev 
still couldn't find it. 

thoughts?

**Comment by tsp-kucbd** [comment]
So, essentially your mash installation does not work.
How did you install mash? If it is via conda, then the library dependencies should be seen to automatically. If you installed it by hand, you would need to double check that it is compiled against the correct library. 
One solution would be to compile mash on your computer ...

**Comment by raw937** [comment]
Installed with conda - that worked. Don't know what this error is.

**Comment by tsp-kucbd** [comment]
Can you try the following commands?
`which mash`
`ldd $(which mash)`
`mash -h`
This should give you information of where to start.

**Comment by raw937** [comment]
mash -h
mash: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory

ldd $(which mash)
	linux-vdso.so.1 (0x00007cf5af48e000)
	libgsl.so.25 => not found
	libcblas.so.3 => /home/docwhite/miniconda3/envs/taxmyphage/bin/../lib/libcblas.so.3 (0x00007cf5ad000000)
	libstdc++.so.6 => /home/docwhite/miniconda3/envs/taxmyphage/bin/../lib/libstdc++.so.6 (0x00007cf5ace1d000)
	libz.so.1 => /home/docwhite/miniconda3/envs/taxmyphage/bin/../lib/libz.so.1 (0x00007cf5af39f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007cf5af39a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007cf5af393000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007cf5af2ac000)
	libgcc_s.so.1 => /home/docwhite/miniconda3/envs/taxmyphage/bin/../lib/libgcc_s.so.1 (0x00007cf5af28d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007cf5aca00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007cf5af490000)
	libgfortran.so.5 => /home/docwhite/miniconda3/envs/taxmyphage/bin/../lib/./libgfortran.so.5 (0x00007cf5acc78000)
	libquadmath.so.0 => /home/docwhite/miniconda3/envs/taxmyphage/bin/../lib/././libquadmath.so.0 (0x00007cf5af253000)

**Comment by sandraaran** [comment]
Hi, I’m encountering the same problem when running the program using the Dockerfile from your repository. Do you have a solution for the "IndexError: list index out of range"? 
I updated Mash and other programs via the Dockerfile, but the problem still persists. 


The error is : File "/opt/conda/lib/python3.12/site-packages/taxmyphage/__main__.py", line 124, in main
    all_classification(
  File "/opt/conda/lib/python3.12/site-packages/taxmyphage/actions.py", line 140, in all_classification
    mash_df, accession_genus_dict = classification_mash(
                                    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/taxmyphage/classify.py", line 187, in classification_mash
    keys = [k for k, v in accession_genus_dict.items() if v == unique_genera[0]]
                                                               ~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by rdenise** [comment]
Hi @sandraaran, the Dockerfile was never tested and might not work sorry

**Comment by pdhrati02** [comment]
Hi, I was wondering if this issue was resolved. I tried downloading the latest version and also by downgrading to v0.3.2. The install works fine but when checking for mash it throws an error: 
mash --version
mash: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
This is because gsl .27 is installed 
added / updated specs:
    - taxmyphage=0.3.2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fonttools-4.59.0           |  py312h8a5da7c_0         2.7 MB  conda-forge
    libexpat-2.7.1             |       hecca717_0          73 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.8 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  asttokens          conda-forge/noarch::asttokens-3.0.0-pyhd8ed1ab_1
  biopython          conda-forge/linux-64::biopython-1.85-py312h66e93f0_1
  blast              bioconda/linux-64::blast-2.16.0-h66d330f_5
  brotli             conda-forge/linux-64::brotli-1.1.0-hb9d3cd8_3
  brotli-bin         conda-forge/linux-64::brotli-bin-1.1.0-hb9d3cd8_3
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h4bc722e_7
  c-ares             conda-forge/linux-64::c-ares-1.34.5-hb9d3cd8_0
  ca-certificates    conda-forge/noarch::ca-certificates-2025.7.14-hbd8a1cb_0
  capnproto          conda-forge/linux-64::capnproto-1.0.2-h766bdaa_3
  colorama           conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_1
  contourpy          conda-forge/linux-64::contourpy-1.3.2-py312h68727a3_0
  curl               conda-forge/linux-64::curl-8.14.1-h332b0f4_0
  cycler             conda-forge/noarch::cycler-0.12.1-pyhd8ed1ab_1
  entrez-direct      bioconda/linux-64::entrez-direct-22.4-he881be0_0
  et_xmlfile         conda-forge/noarch::et_xmlfile-2.0.0-pyhd8ed1ab_1
  executing          conda-forge/noarch::executing-2.2.0-pyhd8ed1ab_0
  fonttools          conda-forge/linux-64::fonttools-4.59.0-py312h8a5da7c_0
  freetype           conda-forge/linux-64::freetype-2.13.3-ha770c72_1
  gsl                pkgs/main/linux-64::gsl-2.7.1-h6e86dc7_1
  icecream           conda-forge/noarch::icecream-2.1.5-pyhd8ed1ab_0
  icu                conda-forge/linux-64::icu-75.1-he02047a_0
  importlib-metadata conda-forge/noarch::importlib-metadata-6.10.0-pyha770c72_0
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0
  kiwisolver         conda-forge/linux-64::kiwisolver-1.4.8-py312h68727a3_1
  krb5               conda-forge/linux-64::krb5-1.21.3-h659f571_0
  lcms2              conda-forge/linux-64::lcms2-2.17-h717163a_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.44-h1423503_1
  lerc               conda-forge/linux-64::lerc-4.0.0-h0aef613_1
  libasprintf        conda-forge/linux-64::libasprintf-0.25.1-h8e693c7_0
  libblas            conda-forge/linux-64::libblas-3.9.0-32_h59b9bed_openblas
  libbrotlicommon    conda-forge/linux-64::libbrotlicommon-1.1.0-hb9d3cd8_3
  libbrotlidec       conda-forge/linux-64::libbrotlidec-1.1.0-hb9d3cd8_3
  libbrotlienc       conda-forge/linux-64::libbrotlienc-1.1.0-hb9d3cd8_3
  libcblas           conda-forge/linux-64::libcblas-3.9.0-32_he106b2a_openblas
  libcurl            conda-forge/linux-64::libcurl-8.14.1-h332b0f4_0
  libdeflate         conda-forge/linux-64::libdeflate-1.24-h86f0d12_0
  libedit            conda-forge/linux-64::libedit-3.1.20250104-pl5321h7949ede_0
  libev              conda-forge/linux-64::libev-4.33-hd590300_2
  libexpat           conda-forge/linux-64::libexpat-2.7.1-hecca717_0
  libffi             conda-forge/linux-64::libffi-3.4.6-h2dba641_1
  libfreetype        conda-forge/linux-64::libfreetype-2.13.3-ha770c72_1
  libfreetype6       conda-forge/linux-64::libfreetype6-2.13.3-h48d6fc4_1
  libgcc             conda-forge/linux-64::libgcc-15.1.0-h767d61c_3
  libgcc-ng          conda-forge/linux-64::libgcc-ng-15.1.0-h69a702a_3
  libgettextpo       conda-forge/linux-64::libgettextpo-0.25.1-h5888daf_0
  libgfortran        conda-forge/linux-64::libgfortran-15.1.0-h69a702a_3
  libgfortran5       conda-forge/linux-64::libgfortran5-15.1.0-hcea5267_3
  libgomp            conda-forge/linux-64::libgomp-15.1.0-h767d61c_3
  libidn2            conda-forge/linux-64::libidn2-2.3.8-ha4ef2c3_0
  libjpeg-turbo      conda-forge/linux-64::libjpeg-turbo-3.1.0-hb9d3cd8_0
  liblapack          conda-forge/linux-64::liblapack-3.9.0-32_h7ac8fdf_openblas
  liblzma            conda-forge/linux-64::liblzma-5.8.1-hb9d3cd8_2
  libnghttp2         conda-forge/linux-64::libnghttp2-1.64.0-h161d5f1_0
  libnsl             conda-forge/linux-64::libnsl-2.0.1-hb9d3cd8_1
  libopenblas        conda-forge/linux-64::libopenblas-0.3.30-pthreads_h94d23a6_0
  libpng             conda-forge/linux-64::libpng-1.6.50-h943b412_0
  libsqlite          conda-forge/linux-64::libsqlite-3.50.2-hee844dc_2
  libssh2            conda-forge/linux-64::libssh2-1.11.1-hcf80075_0
  libstdcxx          conda-forge/linux-64::libstdcxx-15.1.0-h8f9b012_3
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-15.1.0-h4852527_3
  libtiff            conda-forge/linux-64::libtiff-4.7.0-hf01ce69_5
  libunistring       conda-forge/linux-64::libunistring-0.9.10-h7f98852_0
  libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0
  libwebp-base       conda-forge/linux-64::libwebp-base-1.6.0-hd42ef1d_0
  libxcb             conda-forge/linux-64::libxcb-1.17.0-h8a09558_0
  libxcrypt          conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1
  libzlib            conda-forge/linux-64::libzlib-1.3.1-hb9d3cd8_2
  mash               bioconda/linux-64::mash-2.3-hb105d93_9
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.10.3-py312hd3ec401_0
  munkres            conda-forge/noarch::munkres-1.1.4-pyhd8ed1ab_1
  ncbi-vdb           bioconda/linux-64::ncbi-vdb-3.2.1-h9948957_0
  ncurses            conda-forge/linux-64::ncurses-6.5-h2d0b736_3
  networkx           conda-forge/noarch::networkx-3.5-pyhe01879c_0
  numpy              conda-forge/linux-64::numpy-1.26.4-py312heda63a1_0
  openjpeg           conda-forge/linux-64::openjpeg-2.5.3-h5fbd93e_0
  openpyxl           conda-forge/linux-64::openpyxl-3.1.5-py312h710cb58_1
  openssl            conda-forge/linux-64::openssl-3.5.1-h7b32b05_0
  packaging          conda-forge/noarch::packaging-25.0-pyh29332c3_1
  pandas             conda-forge/linux-64::pandas-2.3.1-py312hf79963d_0
  patsy              conda-forge/noarch::patsy-1.0.1-pyhd8ed1ab_1
  perl               conda-forge/linux-64::perl-5.32.1-7_hd590300_perl5
  perl-archive-tar   bioconda/noarch::perl-archive-tar-3.04-pl5321hdfd78af_0
  perl-carp          conda-forge/noarch::perl-carp-1.50-pl5321hd8ed1ab_0
  perl-common-sense  conda-forge/noarch::perl-common-sense-3.75-pl5321hd8ed1ab_0
  perl-compress-raw~ conda-forge/linux-64::perl-compress-raw-bzip2-2.201-pl5321hbf60520_1
  perl-compress-raw~ conda-forge/linux-64::perl-compress-raw-zlib-2.202-pl5321hadc24fc_0
  perl-encode        conda-forge/linux-64::perl-encode-3.21-pl5321hb9d3cd8_1
  perl-exporter      conda-forge/noarch::perl-exporter-5.74-pl5321hd8ed1ab_0
  perl-exporter-tiny conda-forge/noarch::perl-exporter-tiny-1.002002-pl5321hd8ed1ab_0
  perl-extutils-mak~ conda-forge/noarch::perl-extutils-makemaker-7.70-pl5321hd8ed1ab_0
  perl-io-compress   bioconda/linux-64::perl-io-compress-2.201-pl5321h503566f_5
  perl-io-zlib       bioconda/noarch::perl-io-zlib-1.15-pl5321hdfd78af_1
  perl-json          bioconda/noarch::perl-json-4.10-pl5321hdfd78af_1
  perl-json-xs       bioconda/linux-64::perl-json-xs-4.03-pl5321h9948957_4
  perl-list-moreuti~ bioconda/noarch::perl-list-moreutils-0.430-pl5321hdfd78af_0
  perl-list-moreuti~ bioconda/linux-64::perl-list-moreutils-xs-0.430-pl5321h7b50bb2_5
  perl-parent        conda-forge/noarch::perl-parent-0.243-pl5321hd8ed1ab_0
  perl-pathtools     conda-forge/linux-64::perl-pathtools-3.75-pl5321hb9d3cd8_2
  perl-scalar-list-~ conda-forge/linux-64::perl-scalar-list-utils-1.69-pl5321hb9d3cd8_0
  perl-storable      conda-forge/linux-64::perl-storable-3.15-pl5321hb9d3cd8_2
  perl-types-serial~ bioconda/noarch::perl-types-serialiser-1.01-pl5321hdfd78af_0
  pillow             conda-forge/linux-64::pillow-11.3.0-py312h80c1187_0
  pip                conda-forge/noarch::pip-25.1.1-pyh8b19718_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-hb9d3cd8_1002
  pygments           conda-forge/noarch::pygments-2.19.2-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.2.3-pyhd8ed1ab_1
  python             conda-forge/linux-64::python-3.12.11-h9e4cc4f_0_cpython
  python-dateutil    pkgs/main/linux-64::python-dateutil-2.9.0post0-py312h06a4308_2
  python-tzdata      conda-forge/noarch::python-tzdata-2025.2-pyhd8ed1ab_0
  python-wget        conda-forge/noarch::python-wget-3.2-py_0
  python_abi         conda-forge/linux-64::python_abi-3.12-6_cp312
  pytz               conda-forge/noarch::pytz-2025.2-pyhd8ed1ab_0
  qhull              conda-forge/linux-64::qhull-2020.2-h434a139_5
  readline           conda-forge/linux-64::readline-8.2-h8c095d6_2
  rpsbproc           bioconda/linux-64::rpsbproc-0.5.0-hd6d6fdc_3
  scipy              conda-forge/linux-64::scipy-1.16.0-py312hf734454_0
  seaborn            conda-forge/noarch::seaborn-0.13.2-hd8ed1ab_3
  seaborn-base       conda-forge/noarch::seaborn-base-0.13.2-pyhd8ed1ab_3
  setuptools         conda-forge/noarch::setuptools-80.9.0-pyhff2d567_0
  six                conda-forge/noarch::six-1.17.0-pyhd8ed1ab_0
  statsmodels        conda-forge/linux-64::statsmodels-0.14.5-py312h8b63200_0
  taxmyphage         bioconda/noarch::taxmyphage-0.3.2-pyhdfd78af_0
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_hd72426e_102
  tqdm               conda-forge/noarch::tqdm-4.67.1-pyhd8ed1ab_1
  tzdata             conda-forge/noarch::tzdata-2025b-h78e105d_0
  unicodedata2       conda-forge/linux-64::unicodedata2-16.0.0-py312h66e93f0_0
  wget               conda-forge/linux-64::wget-1.21.4-hda4d442_0
  wheel              conda-forge/noarch::wheel-0.45.1-pyhd8ed1ab_1
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.12-hb9d3cd8_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.5-hb9d3cd8_0
  zipp               conda-forge/noarch::zipp-3.23.0-pyhd8ed1ab_0
  zlib               conda-forge/linux-64::zlib-1.3.1-hb9d3cd8_2
  zstd               conda-forge/linux-64::zstd-1.5.7-hb8e6e7a_2


And thus further run fails without taxonomy. Trying to install 0.25 for gsl throws error:
conda install gsl=2.5
Channels:
 - defaults
 - conda-forge
 - bioconda
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package mash-2.3-hb105d93_9 requires gsl >=2.7,<2.8.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ gsl 2.5**  is requested and can be installed;
└─ taxmyphage 0.3.2**  is not installable because it requires
   └─ mash >=2.3,<3.0.0  but there are no viable options
      ├─ mash 2.3 would require
      │  └─ gsl >=2.7,<2.8.0a0 , which conflicts with any installable versions previously reported;
      └─ mash 2.3 would require
         └─ gsl >=2.6,<2.7.0a0 , which conflicts with any installable versions previously reported.

Can you please help resolve this issue? I tried both mamba and conda to install taxmyphage. Any help would be appreciated. 
Thank you
