### ISSUE TITLE
VMR39 v2 sheet number changed from 0 to 1

### ISSUE THREAD

**Issue by igortru** [amillard/tax_myPHAGE#19]
Traceback (most recent call last):
  File "/home/ubuntu/myenv/bin/taxmyphage", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/current/tax_myPHAGE/taxmyphage/__main__.py", line 109, in main
    taxa_df = read_VMR(VMR_path=vmr_path)
  File "/home/ubuntu/current/tax_myPHAGE/taxmyphage/handle_files.py", line 114, in read_VMR
    taxa_df["Genbank"] = taxa_df["Genbank"].fillna("")
  File "/home/ubuntu/myenv/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ubuntu/myenv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Genbank'

def read_VMR(VMR_path: str) -> pd.DataFrame:
    """Reads the VMR data

    Args:
        VMR_path (str): Path to the VMR data

    Returns:
        pd.DataFrame: DataFrame containing the VMR data
    """

    **taxa_df = pd.read_excel(VMR_path, sheet_name=1)** fix , was : 0

    # Print the DataFrame and rename a column
    # ic(taxa_df.head())
        
    # Rename the columns depending on the version of the VMR
    taxa_df = taxa_df.rename( 
        columns={"Virus GENBANK accession": "Genbank", "Genome_id": "Genbank"}
    )
    taxa_df["Genbank"] = taxa_df["Genbank"].fillna("")

    return taxa_df

**Comment by amillard** [comment]
Thanks Igor.  were aware of the issue. Will push a fix when we have checked the other reformatting issues in the new VMR format
